---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: ssh://git@github.com/pandorum-system/infrastructure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomizations
  namespace: flux-system
spec:
  interval: 5m0s
  retryInterval: 2m0s
  timeout: 5m0s
  path: ./clusters/home/kustomizations
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
